In [ ]:
# While in argo environment: Import necessary packages for this notebook 
import numpy as np
from matplotlib import pyplot as plt
import xarray as xr
import pandas as pd
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
%matplotlib inline 

In [12]:
!conda install -c conda-forge dask-xgboost #??? # to install dask

^C


In [11]:
# Choose float and data directory
#rootdir = '/Users/Clara Douglas/OneDrive - University of Southampton/PhD/NitrateDrawdown/Data/'
# path for file 
# Data/9099SOOCN_HRQC.nc
# Data/LowRes/9099SOOCNQC.nc

float_id = '9099' # '9094'
HRfd = xr.open_mfdataset('../data/raw/' + float_id + 'SOOCN_HRQC.nc') # open multiple files as a single dataset
#LRfd =  xr.open_mfdataset('Data/LowRes/' + float_id + 'SOOCNQC.nc') 
JULDHR = pd.to_datetime(HRfd.JULD.values) # convert JULD to date time form
#JULDLR = pd.to_datetime(LRfd.JULD.values) # convert JULD to date time form

ModuleNotFoundError: No module named 'dask'

In [3]:
# help/ find documentation for code
#help(pd.to_datetime)
HRfd
LRfd

<xarray.Dataset>
Dimensions:              (NPARAMETER: 46, N_LEVELS: 67, N_PROF: 188)
Dimensions without coordinates: NPARAMETER, N_LEVELS, N_PROF
Data variables:
    Cruise               |S11 ...
    Station              (N_PROF) int32 dask.array<chunksize=(188,), meta=np.ndarray>
    Lon                  (N_PROF) float64 dask.array<chunksize=(188,), meta=np.ndarray>
    Lat                  (N_PROF) float64 dask.array<chunksize=(188,), meta=np.ndarray>
    Lat_QF               (N_PROF) |S1 dask.array<chunksize=(188,), meta=np.ndarray>
    Lat_QFA              (N_PROF) float64 dask.array<chunksize=(188,), meta=np.ndarray>
    Pressure             (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Pressure_QF          (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Pressure_QFA         (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Temperature          (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Temperature_QF       (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Temperature_QFA      (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Salinity             (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Salinity_QF          (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Salinity_QFA         (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Sigma_theta          (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Sigma_theta_QF       (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Sigma_theta_QFA      (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Depth                (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Depth_QF             (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Depth_QFA            (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Oxygen               (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Oxygen_QF            (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Oxygen_QFA           (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    OxygenSat            (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    OxygenSat_QF         (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    OxygenSat_QFA        (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Nitrate              (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Nitrate_QF           (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Nitrate_QFA          (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Chl_a                (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Chl_a_QF             (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Chl_a_QFA            (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Chl_a_corr           (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Chl_a_corr_QF        (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    Chl_a_corr_QFA       (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    b_bp700              (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    b_bp700_QF           (N_PROF, N_LEVELS) |S1 dask.array<chunksize=(188, 67), meta=np.ndarray>
    b_bp700_QFA          (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 67), meta=np.ndarray>
    b_bp_corr            (N_PROF, N_LEVELS) float64 dask.array<chunksize=(188, 6

okay - running the code with the low res data works; results are all 0 (zeros) for high res data though...
so now need to compare the formats of the datasets. 

### ncdump in terminal

~~~~~~~~~~~~~~~~~~~~~~~~~
high res
~~~~~~~~~~~~~~~~~~~~~~~~~

HR data - 188 profiles

557 N_LEVELS = depths?

46 parameters

missing data recorded as -1e10



~~~~~~~~~~~~~~~~~~~~~~~~~
low res
~~~~~~~~~~~~~~~~~~~~~~~~~

LR data - 188 profiles

67 N_LEVELS = depths?

46 parameters

missing data recorded as -1e10





N_LEVELS DIFFER - high res has much greater pressure/depth resolution than low res


(Nitrate is low res anyway)


#### see below:


In [4]:
# fd
print('High Res')
HRfd.Pressure.isel(N_PROF=0).values

High Res


array([1598.51, 1498.01, 1399.56, 1299.48, 1199.37, 1099.43,  999.9 ,
        977.4 ,  976.  ,  974.  ,  972.  ,  970.  ,  968.  ,  966.  ,
        964.  ,  962.  ,  960.  ,  958.  ,  956.  ,  954.  ,  952.  ,
        951.5 ,  950.  ,  948.  ,  946.  ,  944.  ,  942.  ,  940.  ,
        938.  ,  936.  ,  934.  ,  932.  ,  930.  ,  928.  ,  926.  ,
        924.  ,  922.  ,  920.  ,  918.  ,  916.  ,  914.  ,  912.  ,
        910.  ,  908.  ,  906.  ,  904.  ,  902.  ,  900.97,  900.  ,
        898.  ,  896.  ,  894.  ,  892.  ,  890.  ,  888.  ,  886.  ,
        884.  ,  882.  ,  880.  ,  878.  ,  876.  ,  874.  ,  872.  ,
        870.  ,  868.  ,  866.  ,  864.  ,  862.  ,  860.  ,  858.  ,
        856.  ,  854.  ,  852.  ,  851.57,  850.  ,  848.  ,  846.  ,
        844.  ,  842.  ,  840.  ,  838.  ,  836.  ,  834.  ,  832.  ,
        830.  ,  828.  ,  826.  ,  824.  ,  822.  ,  820.  ,  818.  ,
        816.  ,  814.  ,  812.  ,  810.  ,  808.  ,  806.  ,  804.  ,
        802.  ,  800

In [5]:
print('Low Res')
LRfd.Pressure.isel(N_PROF=0).values
LRfd.Pressure.isel(N_PROF=0).shape

Low Res


(67,)

In [6]:
help(np.convolve)

Help on function convolve in module numpy:

convolve(a, v, mode='full')
    Returns the discrete, linear convolution of two one-dimensional sequences.
    
    The convolution operator is often seen in signal processing, where it
    models the effect of a linear time-invariant system on a signal [1]_.  In
    probability theory, the sum of two independent random variables is
    distributed according to the convolution of their individual
    distributions.
    
    If `v` is longer than `a`, the arrays are swapped before computation.
    
    Parameters
    ----------
    a : (N,) array_like
        First one-dimensional input array.
    v : (M,) array_like
        Second one-dimensional input array.
    mode : {'full', 'valid', 'same'}, optional
        'full':
          By default, mode is 'full'.  This returns the convolution
          at each point of overlap, with an output shape of (N+M-1,). At
          the end-points of the convolution, the signals do not overlap
          co

In [7]:
zi = np.arange(0, 1600, 5)
print(zi)
zi.shape

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

(320,)

In [8]:
np.interp?

Signature: np.interp(x, xp, fp, left=None, right=None, period=None)
Docstring:
One-dimensional linear interpolation.

Returns the one-dimensional piecewise linear interpolant to a function
with given discrete data points (`xp`, `fp`), evaluated at `x`.

Parameters
----------
x : array_like
    The x-coordinates at which to evaluate the interpolated values.

xp : 1-D sequence of floats
    The x-coordinates of the data points, must be increasing if argument
    `period` is not specified. Otherwise, `xp` is internally sorted after
    normalizing the periodic boundaries with ``xp = xp % period``.

fp : 1-D sequence of float or complex
    The y-coordinates of the data points, same length as `xp`.

left : optional float or complex corresponding to fp
    Value to return for `x < xp[0]`, default is `fp[0]`.

right : optional float or complex corresponding to fp
    Value to return for `x > xp[-1]`, default is `fp[-1]`.

period : None or float, optional
    A period for the x-coordinates. T

In [9]:
print(len(LRfd.Nitrate))

188


In [10]:
np.asarray?

Signature: np.asarray(a, dtype=None, order=None, *, like=None)
Docstring:
Convert the input to an array.

Parameters
----------
a : array_like
    Input data, in any form that can be converted to an array.  This
    includes lists, lists of tuples, tuples, tuples of tuples, tuples
    of lists and ndarrays.
dtype : data-type, optional
    By default, the data-type is inferred from the input data.
order : {'C', 'F', 'A', 'K'}, optional
    Memory layout.  'A' and 'K' depend on the order of input array a.
    'C' row-major (C-style), 
    'F' column-major (Fortran-style) memory representation.
    'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
    'K' (keep) preserve input order
    Defaults to 'C'.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an ar

In [11]:
print(LRfd.Pressure[:,::-1])

<xarray.DataArray 'Pressure' (N_PROF: 188, N_LEVELS: 67)>
dask.array<getitem, shape=(188, 67), dtype=float64, chunksize=(188, 67), chunktype=numpy.ndarray>
Dimensions without coordinates: N_PROF, N_LEVELS
Attributes:
    units:    dbar


In [12]:
#help(np.interp)
#help(np.asarray)

In [13]:
#interpolate the data onto the standard depth grid given by x_int
def interpolate(x_int, xvals, yvals):
    yvals_int = []
    for n in range(0, len(yvals)): #len(yvals) being the number of profiles
        yvals_int.append(np.interp(x_int, xvals[n, :], yvals[n, :]))
    #convert the interpolated data from a list to numpy array
    return np.asarray(yvals_int)

In [14]:
abs.argmin?

Object `abs.argmin` not found.


In [15]:
#.argmin

In [16]:
print(LRfd.Nitrate.shape)
print(len(LRfd.Nitrate))
LRfd.Nitrate.isel(N_PROF=0).values # show values of nitrate for first profile - in rev because deepest measurement first

(188, 67)
188


array([33.13, 33.06, 32.96, 33.03, 33.19, 33.06, 33.06, 33.02, 33.02,
       33.01, 32.99, 32.85, 32.72, 32.81, 32.74, 32.65, 32.67, 32.61,
       32.64, 32.7 , 32.59, 32.59, 32.58, 32.56, 32.6 , 32.6 , 32.68,
       32.53, 32.53, 32.54, 32.5 , 32.6 , 32.51, 32.55, 32.49, 32.54,
       32.62, 32.6 , 32.61, 32.51, 32.39, 32.34, 32.13, 31.86, 32.04,
       31.41, 30.7 , 30.26, 29.76, 29.92, 29.6 , 29.45, 29.3 , 29.53,
       29.41, 29.41, 29.3 , 29.01, 28.66, 28.47, 27.91, 26.24, 22.42,
       20.21, 20.17, 20.29,   nan])

In [17]:
# Interpolate nitrate and poc
zi = np.arange(0, 1600, 5)
nitr_int = interpolate(zi, LRfd.Pressure[:, ::-1], LRfd.Nitrate[:, ::-1])

print(nitr_int[0]) # values for profile 1
print(len(zi))
print(len(nitr_int))

print(zi.shape)
print(nitr_int.shape)

[        nan         nan 20.21313043 20.19811215 21.63459357 24.91861635
 27.31380038 28.26739837 28.64733333 29.10997555 29.35511879 29.41
 29.47370656 29.41409804 29.37322134 29.51912046 29.73389635 29.86431095
 29.86916667 30.27982558 30.59959302 30.95394161 31.32411887 31.65071642
 31.96414925 31.9706002  31.87904374 31.98177677 32.13403846 32.24621795
 32.34347752 32.36468193 32.38588634 32.43807157 32.49771372 32.54791786
 32.59567335 32.60639175 32.60123711 32.60750988 32.6173913  32.58942887
 32.547892   32.52105706 32.49767072 32.5104878  32.54097561 32.53486022
 32.51335484 32.54764123 32.59223984 32.55974659 32.51101365 32.51592593
 32.53650206 32.53611423 32.53143258 32.53       32.53       32.58493896
 32.6681798  32.64091116 32.6        32.6        32.5960032  32.58001599
 32.56402878 32.567428   32.57735849 32.5838269  32.58904067 32.59
 32.59       32.60942153 32.63708753 32.66475352 32.69241952 32.68893293
 32.67368902 32.65844512 32.64320122 32.63765625 32.63468948 32

In [18]:
#help(np.array)

In [19]:
# calculate the vertically integrated data column inventory using the composite trapezoidal rule
def integrate(zi, data, depth_range):
    n_profs = len(data)
    zi_start = abs(zi - depth_range[0]).argmin()
    zi_end =  abs(zi - depth_range[1]).argmin()
    zi_struct = np.ones((n_profs, 1)) * zi[zi_start : zi_end]
    data = data[:, zi_start : zi_end]
    col_inv = []
    for n in range(0, len(data)):
        col_inv.append(np.trapz(data[n,:][~np.isnan(data[n,:])], zi_struct[n,:][~np.isnan(data[n,:])]))
    return col_inv

In [20]:
depth_range=[25,200]
zi_start = abs(zi - depth_range[0]).argmin()
print(zi)
print(depth_range[0])
print(zi_start)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [21]:
depth_range=[25,200]
zi_end = abs(zi - depth_range[1]).argmin()
print(zi)
print(depth_range[1])
print(zi_end)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [22]:
depth_range=[25,200]
zi_start = abs(zi - depth_range[0]).argmin()
print(depth_range[0])
print(zi_start)
zi_end = abs(zi - depth_range[1]).argmin()
print(depth_range[1])
print(zi_end)

n_profs = len(nitr_int)
zi_struct = np.ones((n_profs, 1)) * zi[zi_start : zi_end+1] # could add +1 to get all the way to 200?
print(zi_struct)
zi_struct.shape

25
5
200
40
[[ 25.  30.  35. ... 190. 195. 200.]
 [ 25.  30.  35. ... 190. 195. 200.]
 [ 25.  30.  35. ... 190. 195. 200.]
 ...
 [ 25.  30.  35. ... 190. 195. 200.]
 [ 25.  30.  35. ... 190. 195. 200.]
 [ 25.  30.  35. ... 190. 195. 200.]]


(188, 36)

In [23]:
#np.trapz?
np.where?

Docstring:
where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples
-

In [24]:
zi = np.arange(0, 1600, 2)
print(zi)

[   0    2    4    6    8   10   12   14   16   18   20   22   24   26
   28   30   32   34   36   38   40   42   44   46   48   50   52   54
   56   58   60   62   64   66   68   70   72   74   76   78   80   82
   84   86   88   90   92   94   96   98  100  102  104  106  108  110
  112  114  116  118  120  122  124  126  128  130  132  134  136  138
  140  142  144  146  148  150  152  154  156  158  160  162  164  166
  168  170  172  174  176  178  180  182  184  186  188  190  192  194
  196  198  200  202  204  206  208  210  212  214  216  218  220  222
  224  226  228  230  232  234  236  238  240  242  244  246  248  250
  252  254  256  258  260  262  264  266  268  270  272  274  276  278
  280  282  284  286  288  290  292  294  296  298  300  302  304  306
  308  310  312  314  316  318  320  322  324  326  328  330  332  334
  336  338  340  342  344  346  348  350  352  354  356  358  360  362
  364  366  368  370  372  374  376  378  380  382  384  386  388  390
  392 

In [25]:
# Integrate nitrate and poc
nitr = np.array(integrate(zi, nitr_int, [25, 200]))
print(nitr.shape)
print(nitr.size)
print(nitr)

(188,)
188
[5608.00792359 5677.56254434 5662.09618155 5690.46439613 5708.56369563
 5727.35599175 5722.70244329 5722.52251665 5732.19845281 5734.10749284
 5669.69294854 5725.60481022 5701.77209453 5706.81747595 5726.33332538
 5715.41871353 5726.47399423 5723.32172866 5739.505461   5740.81456984
 5720.93543252 5723.08984279 5725.70346352 5730.43096894 5732.44175782
 5709.2770991  5700.75507111 5727.91737366 5721.98434418 5754.31692212
 5743.63275055 5735.67903933 5741.18465228 5756.75287113 5759.73656526
 5757.85931573 5782.2982231  5734.5321616  5742.71258486 5760.9495855
 5763.18355993 5767.73614487 5747.46281885 5726.58474083 5693.01343656
 5695.55818592 5679.31529544 5706.41910514 5727.4582099  5735.21579771
 5757.42847292 5742.22486234 5742.70026435 5721.26215755 5739.30356708
 5733.63303836 5710.49891131 5718.7738652  5727.56290397 5735.28922267
 5782.57027144 5742.66252416 5746.91211798 5735.70331302 5729.9212869
 5717.88490742 5723.48131814 5729.41779665 5730.06578538 5721.552506

In [26]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [29]:

def find_extrema(data, date_range, find_func):
    # Find indices of float profiles in the date range
    date_mask = (JULDLR > date_range[0]) & (JULDLR < date_range[1])
    
    # Get the index where the data is closest to the find_func
    index = np.where(data[date_mask] == find_func(data[date_mask]))[0][0]
    
    # Get the average data for the month of the extrema
    month_start = JULDLR[date_mask][index].replace(day = 1)
    month_dates = (JULDLR > month_start) & (JULDLR < month_start + pd.Timedelta(days = 30))
    month_avg = np.mean(data[date_mask])
    
    return month_avg, JULDLR[date_mask][index], data[date_mask][index]

years = [2015, 2016, 2017, 2018]
nitr_extrema = []
nitr_ancp = []
for y in years:
    winter_range = [pd.datetime(y, 8, 1), pd.datetime(y, 12, 1)]
    summer_range = [pd.datetime(y, 12, 1), pd.datetime(y + 1, 4, 1)]

    # Find maximum winter and minimum summer nitrate
    avg_max_nitr, max_nitr_date, max_nitr = find_extrema(nitr, winter_range, np.max)
    avg_min_nitr, min_nitr_date, min_nitr = find_extrema(nitr, summer_range, np.min)
    
    # Convert to annual nitrate drawdown
    redfield_ratio = 106.0/16.0 #106C:16NO3-
    
    # Nitrate units: umol/kg
    
    nitr_drawdown = (avg_max_nitr - avg_min_nitr)/1000.0 * redfield_ratio
    
    nitr_ancp.append(nitr_drawdown)
    
    nitr_extrema.append(((max_nitr, max_nitr_date), (min_nitr, min_nitr_date)))
    
    print(y, max_nitr_date, max_nitr, avg_max_nitr)
    print(y, min_nitr_date, min_nitr, avg_min_nitr)
    
print('And ANCP are:', years)
print(nitr_ancp)

2015 2015-11-13 20:23:00.000001536 5754.3169221167445 5727.608299679489
2015 2016-02-05 07:29:00.000003584 5734.532161601182 5754.173960203504
2016 2016-09-28 23:48:59.999999232 5782.57027144283 5733.741140047997
2016 2017-01-19 23:40:00.000001024 5712.145129589457 5731.024857839507
2017 2017-10-25 02:18:59.999995648 5748.612094849316 5700.495989223408
2017 2018-01-05 04:57:00.000004096 5651.350489369697 5684.523072389045
2018 2018-09-08 23:03:59.999999232 5694.41377294887 5669.77656759871
2018 2019-03-23 10:46:00.000003072 5630.868936713724 5667.951900455774
And ANCP are: [2015, 2016, 2017, 2018]
[-0.17599750097159722, 0.017995369631247288, 0.10582057402765406, 0.012088419821951335]


<ipython-input-29-e9fda41346f7>:19: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  winter_range = [pd.datetime(y, 8, 1), pd.datetime(y, 12, 1)]
<ipython-input-29-e9fda41346f7>:20: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  summer_range = [pd.datetime(y, 12, 1), pd.datetime(y + 1, 4, 1)]


In [32]:
JULDLR.month.shape

(188,)

In [34]:
winter_range = [pd.datetime(2015, 8, 1), pd.datetime(2015, 12, 1)]
date_mask = (JULDLR > winter_range[0]) & (JULDLR < winter_range[1])
index = np.where(nitr[date_mask] == np.max(nitr[date_mask]))[0][0]
print(index)
month_start2 = JULDLR[date_mask][index]
month_start = JULDLR[date_mask][index].replace(day = 1)
print(month_start2)
print(month_start)
month_dates = (JULDLR > month_start) & (JULDLR < month_start + pd.Timedelta(days = 30)) 
print(month_dates)
month_dates.shape
#pd.Timedelta?
month_avg = np.mean(nitr[date_mask])
print(month_avg)

10
2015-11-13 20:23:00.000001536
2015-11-01 20:23:00.000001536
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False 

<ipython-input-34-757016c7f65c>:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  winter_range = [pd.datetime(2015, 8, 1), pd.datetime(2015, 12, 1)]


In [35]:
print(month_start.month)
print(month_start)
# for 2015: winter max in month 9
    # index - number 5 within datemask

month_avg = np.mean(nitr[date_mask])     
print(month_avg)
#month_ave = np.mean(nitr[date_mask] where month = month_start.month)

print(date_mask)

11
2015-11-01 20:23:00.000001536
5727.608299679489
[False False False False False False False False False False False False
 False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False


In [37]:
month_mask = (JULDLR.month == month_start.month) & (JULDLR.year == month_start.year)

month_mask2 = (JULDLR.month[date_mask] == month_start.month)

#month_mask = (JULDLR.month == month_start.month)
#month_mask = (JULDLR == month_start.year)
print(month_mask)
print(month_mask2)

#print(month_start.year)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [38]:
month_avg = np.mean(nitr[month_mask])
print(month_avg)

5739.978005616123


In [ ]:
help(plt.axvspan)

In [ ]:
#try to integrate using high res data
print(HRfd.Pressure.shape)
print(HRfd.Pressure.size)
print('High Res')
HRfd.Pressure.isel(N_PROF=1).values

In [ ]:
# Integrate nitrate and poc
nitr = np.array(integrate(zi, nitr_int, [25, 200])) # integrate interpolated nitrate values between 25m-200m




In [ ]:
# my 'years' range
timeseries = np.arange(2002, 2021, 1)
print(timeseries)

In [ ]:
#HRfd.Lat.isel(N_PROF=0).values #for just one profile
HRfd.Lat.values

In [ ]:
zi = np.arange(0, 1600, 5) # 5 = 320 depth intervals between 0m to 1595m
nitr_int = interpolate(zi, HRfd.Pressure[:, ::-1], HRfd.Nitrate[:, ::-1]) # interpolate nitrate values across zi depth intervals for all 188 profiles

# Integrate nitrate and poc - total nitrate in upper 200m
upperlim=25
lowerlim=200
nitr = np.array(integrate(zi, nitr_int, [upperlim, lowerlim])) # integrate interpolated nitrate values between 25m-200m 

print(nitr_int[0])
#HRfd.nitr_int.isel(N_PROF=0).values

In [ ]:
HRfd.Pressure[:, ::-1].values

In [ ]:
zi = np.arange(0, 1600, 5) # 5 = 320 depth intervals between 0m to 1595m
nitr_int = interpolate(zi, LRfd.Pressure[:, :], LRfd.Nitrate[:, :]) # interpolate nitrate values across zi depth intervals for all 188 profiles

# Integrate nitrate and poc - total nitrate in upper 200m
upperlim=25
lowerlim=200
nitr = np.array(integrate(zi, nitr_int, [upperlim, lowerlim])) # integrate interpolated nitrate values between 25m-200m 

print(nitr_int[10,9])

#print(nitr)
print(nitr_int.shape)